# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30, unique=True)),
                ('post_text', models.TextField(max_length=500)),
                ('post_date', models.DateField(auto_now=True)),
                ('post_image', models.ImageField(blank=True, default='', upload_to='blog_app/post_images')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Post'),
        ),
    ]
