# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20160921_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribed_user',
            new_name='subscribe_user',
        ),
    ]
