# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20160921_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
